//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by his3.rc
//
#define IDC_BUTTON_PRINT                3
#define IDOK_YB                         3
#define IDOK_ADD                        3
#define IDOK_QUERY                      3
#define IDOK2                           3
#define ID_BUTTON_EXCEL                 3
#define IDOK_RY1                        5
#define IDOK4                           5
#define IDOK_RY2                        6
#define IDOK_RY3                        7
#define IDD_ABOUTBOX                    100
#define IDD_FORM_USED_ALL               102
#define IDR_REPORTUSEDALL_TMPL          103
#define IDR_MAINFRAME                   128
#define IDR_HIS3TYPE                    129
#define IDD_DIALOG_SPLASH               131
#define IDD_DIALOG_INDICATE             132
#define IDD_DIALOG1                     133
#define IDD_DIALOG_GH                   133
#define IDB_BITMAP_LOGON                134
#define IDD_DIALOG_LOGON                135
#define IDD_DIALOG_HJ                   138
#define IDD_MED_STOCKLIST               140
#define IDR_MENU_QUICK                  142
#define IDD_DIALOG_OTHER_EXES           143
#define IDD_DIALOG_ACCOUNT_QUERY        145
#define IDD_FORM_GHLIST                 147
#define IDD_DIALOG_GH_QUERY             149
#define IDI_ICON_QUERY                  151
#define IDD_DIALOG_REPORT_VIEW          153
#define IDD_DIALOG_GETMED               155
#define IDD_DIALOG_PERSON_QUERY         158
#define IDD_DIALOG_WAIT                 160
#define IDD_DIALOG_PRIVILEGE            161
#define IDD_DIALOG_UPGRADE              163
#define IDD_DIALOG_LOCK                 164
#define IDD_FORM_GHLIST_DEL             165
#define IDD_DIALOG_CLASS_A              168
#define IDD_DIALOG_COST_ADD             170
#define IDD_DIALOG_COST_2_ADD           171
#define IDD_DIALOG_COST_BUDGET          172
#define IDD_DIALOG_COST_BUDGET_ADD      174
#define IDD_OPERATOR_SEL                175
#define IDD_FORM_DECHARGELIST           177
#define IDD_DIALOG_DECHARGE_QUERY       179
#define IDD_DIALOG_BCYB_CX              181
#define IDD_DIALOG_BUZU                 182
#define IDD_DIALOG_MED_CODE             184
#define IDD_DIALOG_MED_CODE_MODIFY      186
#define IDD_DIALOG_MEDQUERY             187
#define IDD_DIALOG_BCBX_ZJB             188
#define IDD_FORM_MED_CONSUME            192
#define IDD_DIALOG_QUERY_CONSUME        194
#define IDD_DIALOG_PLANASWHOLE          195
#define IDD_DIALOG_AFFINITY_QUERY       196
#define IDD_DIALOG_EMP_QUERY            197
#define IDD_DIALOG_RELATE_QUERY         198
#define IDC_PROGRESS_SPLASH             1000
#define IDC_PROGRESS1                   1001
#define IDC_COMBO1                      1002
#define IDC_COMBO2                      1003
#define IDC_COMBO3                      1004
#define IDC_COMBO_SEX                   1004
#define IDC_COMBO_EMP_STA               1004
#define IDC_EDIT1                       1005
#define IDC_EDIT2                       1006
#define IDC_EDIT_KH                     1006
#define IDC_EDIT_TYPE                   1006
#define IDC_EDIT_MESSAGE                1006
#define IDC_EDIT_KXM                    1006
#define IDC_EDIT_XM                     1006
#define IDC_EDIT_ORDER                  1006
#define IDC_EDIT_SEQ                    1006
#define IDC_EDIT_RSS                    1006
#define IDC_EDIT_YSR                    1006
#define IDC_EDITC_XM                    1006
#define IDC_EDIT_BM                     1006
#define IDC_EDIT_GG                     1006
#define IDC_EDIT3                       1007
#define IDC_STATIC_BMP                  1007
#define IDC_EDIT_NAME                   1007
#define IDC_EDIT_SFY                    1007
#define IDC_EDIT_CMT                    1007
#define IDC_EDIT_REM                    1007
#define IDC_EDIT_JSR                    1007
#define IDC_EDIT_DW                     1007
#define IDC_BUTTON_OK                   1008
#define IDC_EDIT_SEX                    1008
#define IDC_EDIT_SPR                    1008
#define IDC_EDIT_PY1                    1008
#define IDC_BUTTON_CANCEL               1009
#define IDC_EDITHJ_AGE                  1009
#define IDC_EDIT_PIAOJU                 1009
#define IDC_EDIT_MAXKC                  1009
#define IDC_EDIT_AGE                    1010
#define IDC_EDIT_PY                     1010
#define IDC_EDIT_FUJIAN                 1010
#define IDC_EDIT_MINKC                  1010
#define IDC_BUTTON_ADD                  1011
#define IDC_EDIT_NUM                    1011
#define IDC_EDIT_ZHONGFEIYONG           1011
#define IDC_EDIT_BZ                     1011
#define IDC_COMBO_GH_TYPE               1012
#define IDC_EDIT_MC                     1012
#define IDC_EDIT_SCALE                  1012
#define IDC_BUTTON_GRID_DEL             1013
#define IDC_EDIT_CASH                   1013
#define IDC_EDIT_SJBS                   1013
#define IDC_MSHFLEXGRID1                1014
#define IDC_EDIT_BALANCE                1014
#define IDC_MSHFLEXGRID2                1015
#define IDC_EDIT_ADDRESS                1015
#define IDC_EDIT_BALANCE2               1015
#define IDC_EDIT_YS                     1016
#define IDC_EDIT_CREDENCE               1016
#define IDC_BUTTON_S_ADD                1017
#define IDC_EDIT_TC                     1017
#define IDC_BUTTON_A_ADD                1018
#define IDC_EDIT_IC                     1018
#define IDC_BUTTON_S_DEL                1019
#define IDC_EDIT_GWY                    1019
#define IDC_BUTTON_A_DEL                1020
#define IDC_EDIT_JGC                    1020
#define IDC_COMBO_TYPE                  1021
#define IDC_EDIT_DBJZ                   1021
#define IDC_MSHFLEXGRID_SRC             1022
#define IDC_MSHFLEXGRID3                1022
#define IDC_MSHFLEXGRID_DST             1023
#define IDC_EDIT_ACCOUNT                1023
#define IDC_EDIT_COST                   1024
#define IDC_EDIT_QKH                    1025
#define IDC_EDIT_WORKUNIT               1025
#define IDBUTTON_ADD                    1026
#define IDC_EDIT_RATIO                  1026
#define IDC_EDIT_YUER                   1027
#define IDC_STATIC_TITLE                1028
#define IDC_EDIT_REAL_SS                1028
#define IDC_DATETIMEPICKER1             1029
#define IDC_EDIT_REAL_ZL                1029
#define IDC_DATETIMEPICKER2             1030
#define IDC_EDIT_CHINA_MED              1030
#define IDC_COMBO_MED_STATUS            1031
#define IDC_STATIC_EMP_STA              1032
#define IDBUTTON_TOEXCEL                1033
#define IDC_BUTTON_QUERY                1034
#define IDC_EDIT_ID                     1035
#define IDC_STATIC_1                    1036
#define IDC_STATIC_2                    1037
#define IDC_STATIC_3                    1038
#define IDC_STATIC_VER                  1039
#define IDC_STATIC_IC                   1040
#define IDC_STATIC_VER2                 1040
#define IDC_STATIC1                     1041
#define IDC_STATIC2                     1042
#define IDC_EDIT_PASSWORD               1043
#define IDC_STATIC_KS                   1044
#define IDC_STATIC_XM                   1045
#define IDC_EDIT_NAME1                  1046
#define IDC_COMBO_YEAR                  1047
#define IDC_EDIT_CMMT                   1048
#define IDC_COMBO_COST_A                1049
#define IDC_COMBO_COST_B                1050
#define IDC_DATETIMEPICKER_CUR          1052
#define IDC_COMBO_DEP_SEL               1053
#define IDB_SEL                         1054
#define IDC_EDIT_100SCALE               1055
#define IDC_EDIT_USER                   1056
#define IDC_BUTTON_JSR                  1057
#define IDC_BUTTON_RSR                  1058
#define IDC_BUTTON_SPR                  1059
#define IDC_COMBO_A                     1060
#define IDC_COMBO_B                     1061
#define IDC_EDIT_SYR                    1062
#define IDC_EDITC_KH                    1066
#define IDEXCEL                         1067
#define IDOK_EXCEL_IN                   1068
#define IDOK_EXECUTE_ADD                1069
#define IDOK_MODIFY                     1070
#define IDC_COMBO_KF                    1071
#define IDC_CHECK1                      1072
#define IDC_EDIT_KH0                    1073
#define IDC_EDIT_ACCURAL                1074
#define IDC_CUSTOM_GRID                 1075
#define IDC_COMBO_DEPART                1076
#define ID_MENUITEM32771                32771
#define ID_MENUITEM32772                32772
#define ID_MENUITEM_GHOPER              32772
#define ID_001_001                      32774
#define ID_BUTTON32777                  32777
#define ID_MENUITEM32778                32778
#define ID_MENUITEM32779                32779
#define ID_MENU_GH_GETMED               32780
#define ID_MENUITEM_HJ_SEL_DEL          32781
#define ID_MENUITEM_HJ_ALL_DEL          32782
#define ID_MENUITEM_G2S_DEL             32783
#define ID_MENUITEM_G2A_DEL             32784
#define ID_MENUITEM_MED_MODIFY          32785
#define ID_MENUITEM_OTHER_MODIFY        32786
#define ID_MENU_REPORT_VIEW             32787
#define ID_MENUITEM32788                32788
#define ID_MENUITEM_ACCOUNT_MODIFY      32789
#define ID_MENUITEM_ACCOUNT_SDEL        32790
#define ID_MENUITEM_ACCOUNT_ADEL        32791
#define ID_MENU_REPORT_MZCX             32792
#define ID_MENU_GH_VIEWLIST             32793
#define ID_MENU_GH_LISTTOEXCEL          32794
#define ID_MENU_GH_DELETE               32795
#define ID_MENU_SYS_PRIVI_SET           32796
#define ID_MENU_BASE_DEPART_SET         32797
#define ID_MENU_BASE_DEPART2_SET        32798
#define ID_MENU_LOCK                    32800
#define ID_MENU_REPORT_DEL_MZCQ         32801
#define ID_MENU_REPORT_BCBX_HZ          32802
#define ID_MENU_COST_CLASS_A            32803
#define ID_MENU_COST_CLASS_B            32804
#define ID_MENU_COST_ADD                32805
#define ID_MENU_COST_MODIFY             32806
#define ID_MENU_COST_DEL                32807
#define ID_MENU_COST_RESTORE            32808
#define ID_MENU_COST_2_ADD              32809
#define ID_MENU_COST_2_MODIFY           32810
#define ID_MENU_COST_2_RESTORE          32811
#define ID_MENU_COST_2_DEL              32812
#define ID_MENU_COST_BUDGET             32813
#define ID_MENU_COST_CONSUME            32814
#define ID_MENU_REPORT_DECHARGE         32815
#define ID_MENUITEM_REPORT_EXCEL        32816
#define ID_MENUITEM_REPORT_DEL          32817
#define ID_MENUITEM_PECULIAR_ADD        32818
#define ID_MENUITEM_MED_QUERY           32819
#define ID_MENU_MEDCODE_MANAGER         32820
#define ID_MENUITEM_BCYB_ZJB            32821
#define ID_MENUITEM_BCYB_JSB            32822
#define ID_MENUITEM_MED_CONSUME         32823
#define ID_MENU_MEDCODE_SORT            32824
#define ID_MENU_PLANWHOLE               32825
#define ID_MENUITEM_AFFINITY_QUERY      32826
#define ID_MENUITEM_EMP_QUERY           32827
#define ID_MENUITEM_RELATE_QUERY        32828
#define ID_INDICATOR_PROMPT             59142
#define IDS_PRIV_PROMPT                 61446
#define IDS_HUAJIA_PROMPT               61447
#define IDS_STR_VERSION                 61448
#define IDS_STR_UPGRADE_1               61449
#define IDS_STR_UPGRADE_2               61450
#define IDS_STR_WAIT_PROMPT             61451
#define IDS_STR_VERSION2                61452

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        198
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
